template_logo: http://orders.confidentcannabis.com/assets/img/labs/SPN/black.png
template_scripts:
template_rules:
  - rule:
      package_key:
      package_name: Potency - HPLC/DAD
      included_templates:
        - 5-can-rev-1.pdf
        - 6-pest-rev-1.pdf
        - 7-mic-rev-1.pdf
        - 8-sol-rev-1.pdf
        - 9-ter-rev-1.pdf
  - rule:
      package_key:
      package_name: Pesticide - GC/MS and LC-MS/MS
      included_templates:
        - 5-can-rev-1.pdf
        - 6-pest-rev-1.pdf
        - 7-mic-rev-1.pdf
        - 8-sol-rev-1.pdf
        - 9-ter-rev-1.pdf
  - rule:
      package_key:
      package_name: Microbial - Petrifilm Plating
      included_templates:
        - 5-can-rev-1.pdf
        - 6-pest-rev-1.pdf
        - 7-mic-rev-1.pdf
        - 8-sol-rev-1.pdf
        - 9-ter-rev-1.pdf
  - rule:
      package_key:
      package_name: Residual Solvents - GC-FID
      included_templates:
        - 5-can-rev-1.pdf
        - 6-pest-rev-1.pdf
        - 7-mic-rev-1.pdf
        - 8-sol-rev-1.pdf
        - 9-ter-rev-1.pdf
  - rule:
      package_key:
      package_name: Terpenes - GC/MS and LC-MS/MS
      included_templates:
        - 5-can-rev-1.pdf
        - 6-pest-rev-1.pdf
        - 7-mic-rev-1.pdf
        - 8-sol-rev-1.pdf
        - 9-ter-rev-1.pdf
  - rule:
      package_key:
      package_name: Full Spectrum
      included_templates:
        - 5-can-rev-1.pdf
        - 6-pest-rev-1.pdf
        - 7-mic-rev-1.pdf
        - 8-sol-rev-1.pdf
        - 9-ter-rev-1.pdf