template_logo: http://confidentcannabis.local/assets/img/labs/DEV/black.png
template_scripts:
template_rules:
  - rule:
      package_key:
      package_name: All the Tests
      included_templates:
        - 5-Can.pdf
        - 7-Mic.pdf
        - 8-Sol.pdf
        - 9-Ter.pdf
        - B-Myc.pdf
  - rule:
      package_key:
      package_name: Just Cannabinoids
      included_templates:
        - 5-Can.pdf
