template_logo: http://orders.confidentcannabis.com/assets/img/labs/SCP/color.png
template_scripts:
template_rules:
  -rule:
    package_key:
    package_name: State Required Cannabinoids (GC + MIcro)
    included_templates:
      - new5Can.pdf
      - 7-Mic.pdf
  - rule:
      package_key:
      package_name: State Required Cannabinoids (HPLC + Micro)
      included_templates:
        - 1-new5Can.pdf
        - 7-Mic.pdf
  - rule:
      package_key:
      package_name: Micro Combo
      included_templates:
        - 7-Mic.pdf
  - rule:
      package_key:
      package_name: State Required Cannabinoid Profile (GC Test)
      included_templates:
        - 1-new5Can.pdf
  - rule:
      package_key:
      package_name: State Required Cannabinoid Profile (HPLC Test)
      included_templates:
        - 1-new5Can.pdf
  - rule:
      package_key:
      package_name: Full Cannabinoid Profile
      included_templates:
        - 1-new5Can.pdf
  - rule:
      package_key:
      package_name: Micro Combo
      included_templates:
        - 7-Mic.pdf
  - rule:
      package_key:
      package_name: State Required Cannabinoid Profile (GC + Micro)
      included_templates:
        - new5Can.pdf
        - 7-Mic.pdf
  - rule:
      package_key:
      package_name: State Required Cannabinoid Profile (HPLC + Micro)
      included_templates:
        - 1-new5Can.pdf
        - 7-Mic.pdf
  - rule:
      package_key:
      package_name: Mycotoxins - Quick
      included_templates:
        - B-Myc.pdf
  - rule:
      package_key:
      package_name: Mycotoxins - Full
      included_templates:
        - B-Myc.pdf
  - rule:
      package_key:
      package_name: Terpenes Profile
      included_templates:
        - new9Ter-3.pdf
  - rule:
      package_key:
      package_name: Residual Solvents
      included_templates:
        - 8-Sol.pdf
