template_logo: https://orders.confidentcannabis.com/assets/img/labs/MML/report.png
template_scripts:
template_rules:
  - rule:
      package_key:
      package_name: Potency - HPLC/DAD
      included_templates:
        - SCP-A-CAN-V1.pdf
  - rule:
      package_key:
      package_name: Pesticide - GC/MS and LC-MS/MS
      included_templates:
        - SCP-A-PES-V1.pdf
  - rule:
      package_key:
      package_name: Microbial - Petrifilm Plating
      included_templates:
        - SCP-A-MIC-V1.pdf
  - rule:
      package_key:
      package_name: Residual Solvents - GC-FID
      included_templates:
        - SCP-A-SOL-V1.pdf
  - rule:
      package_key:
      package_name: Terpenes - GC/MS and LC-MS/MS
      included_templates:
        - SCP-A-TER-V1.pdf
  - rule:
      package_key:
      package_name: Full Spectrum
      included_templates:
        - SCP-C-CAN-H2O-ATY-V1.pdf
        - SCP-A-PES-V1.pdf