template_logo: http://orders.confidentcannabis.com/assets/img/labs/SHN/black.png
template_scripts:
template_rules:
  - rule:
      package_key:
      package_name: Placeholder Package
      included_templates:
        - 1-bas-rev-1.pdf
        - 2-saf-rev-1.pdf
        - 5-can-rev-1.pdf
        - 6-pest-rev-1.pdf
        - 7-mic-rev-1.pdf
        - 8-sol-rev-1.pdf
        - 9-ter-rev-1.pdf
        - a-hvy-rev-1.pdf
        - b-myc-rev-1.pdf
  - rule:
      package_key:
      package_name: Flower - State Requirements
      included_templates:
        - 1-bas-rev-1.pdf
        - 2-saf-rev-1.pdf
        - 5-can-rev-1.pdf
        - 6-pest-rev-1.pdf
        - 7-mic-rev-1.pdf
        - 8-sol-rev-1.pdf
        - 9-ter-rev-1.pdf
        - a-hvy-rev-1.pdf
        - b-myc-rev-1.pdf