template_logo: http://orders.confidentcannabis.com/assets/img/labs/SQA/color.png
template_scripts: badges_and_grades.py
template_rules:
  - rule:
      package_key:
      package_name: Potency Analysis GC-FID
      included_templates:
        - GC Report.pdf
  - rule:
      package_key:
      package_name: Potency Analysis GC-FID (Edible)
      included_templates:
        - GC Edible Form.pdf
  - rule:
      package_key:
      package_name: Potency Analysis GC-FID (Tincture)
      included_templates:
        - GC Edible Form.pdf
  - rule:
      package_key:
      package_name: Potency Analysis GC-FID (Infusion)
      included_templates:
        - GC Edible Form.pdf
  - rule:
      package_key:
      package_name: Potency Analysis HPLC
      included_templates:
        - HPLC Report Page 1 Form.pdf
  - rule:
      package_key:
      package_name: Potency Analysis HPLC (Edible)
      included_templates:
        - HPLC Report Edible Form.pdf
  - rule:
      package_key:
      package_name: Potency Analysis HPLC (Tincture)
      included_templates:
        - HPLC Report Edible Form.pdf
  - rule:
      package_key:
      package_name: Potency Analysis HPLC (Infusion)
      included_templates:
        - HPLC Report Edible Form.pdf
  - rule:
      package_key:
      package_name: Pesticide Analysis
      included_templates:
        - HPLC Report Report Page 2 Form.pdf
  - rule:
      package_key:
      package_name: Pesticide Analysis (Tincture)
      included_templates:
        - HPLC Edible Form.pdf
  - rule:
      package_key:
      package_name: Microbiological Analysis
      included_templates:
        - HPLC Report Report Page 2 Form.pdf
  - rule:
      package_key:
      package_name: Microbiological Analysis (Edible)
      included_templates:
        - HPLC Edible Form.pdf
  - rule:
      package_key:
      package_name: Microbiological Analysis (Tincture)
      included_templates:
        - HPLC Edible Form.pdf
  - rule:
      package_key:
      package_name: Microbiological Analysis (Infusion)
      included_templates:
        - HPLC Edible Form.pdf
  - rule:
      package_key:
      package_name: Terpene Analysis
      included_templates:
        - GC Report.pdf
  - rule:
      package_key:
      package_name: Terpene Analysis (Tincture)
      included_templates:
        - GC Edible Form.pdf
  - rule:
      package_key:
      package_name: Residual Solvent Analysis
      included_templates:
        - HPLC Reporting Page 2 Form.pdf
  - rule:
      package_key:
      package_name: Residual Solvent Analysis (Tincture)
      included_templates:
        - HPLC Edible Form.pdf
