template_logo: http://orders.confidentcannabis.com/assets/img/labs/GHA/report.png
template_scripts:
template_rules:
  - rule:
      package_key:
      package_name: Potency
      included_templates:
        - 5-can-rev-1.pdf
  - rule:
      package_key:
      package_name: Pesticides
      included_templates:
        - 6-pest-rev-1.pdf
  - rule:
      package_key:
      package_name: Microbial & Percent Moisture
      included_templates:
        - 5-can-rev-1.pdf
        - 7-mic-rev-1.pdf
  - rule:
      package_key:
      package_name: Microbial
      included_templates:
        - 5-can-rev-1.pdf
        - 7-mic-rev-1.pdf
  - rule:
      package_key:
      package_name: Terpene
      included_templates:
        - 9-ter-rev-1.pdf